@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node42 as "gen_table  /* 代码生成业务表 */" {
   table_name  /* 表名称 */: varchar(200)
   table_comment  /* 表描述 */: varchar(500)
   sub_table_name  /* 关联子表的表名 */: varchar(64)
   sub_table_fk_name  /* 子表关联的外键名 */: varchar(64)
   class_name  /* 实体类名称 */: varchar(100)
   tpl_category  /* 使用的模板（crud单表操作 tree树表操作） */: varchar(200)
   package_name  /* 生成包路径 */: varchar(100)
   module_name  /* 生成模块名 */: varchar(30)
   business_name  /* 生成业务名 */: varchar(30)
   function_name  /* 生成功能名 */: varchar(50)
   function_author  /* 生成功能作者 */: varchar(50)
   gen_type  /* 生成代码方式（0zip压缩包 1自定义路径） */: char(1)
   gen_path  /* 生成路径（不填默认项目路径） */: varchar(200)
   options  /* 其它生成选项 */: varchar(1000)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   table_id  /* 编号 */: bigint(20)
}
class node29 as "gen_table_column  /* 代码生成业务表字段 */" {
   table_id  /* 归属表编号 */: varchar(64)
   column_name  /* 列名称 */: varchar(200)
   column_comment  /* 列描述 */: varchar(500)
   column_type  /* 列类型 */: varchar(100)
   java_type  /* JAVA类型 */: varchar(500)
   java_field  /* JAVA字段名 */: varchar(200)
   is_pk  /* 是否主键（1是） */: char(1)
   is_increment  /* 是否自增（1是） */: char(1)
   is_required  /* 是否必填（1是） */: char(1)
   is_insert  /* 是否为插入字段（1是） */: char(1)
   is_edit  /* 是否编辑字段（1是） */: char(1)
   is_list  /* 是否列表字段（1是） */: char(1)
   is_query  /* 是否查询字段（1是） */: char(1)
   query_type  /* 查询方式（等于、不等于、大于、小于、范围） */: varchar(200)
   html_type  /* 显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件） */: varchar(200)
   dict_type  /* 字典类型 */: varchar(200)
   sort  /* 排序 */: int(11)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   column_id  /* 编号 */: bigint(20)
}
class node36 as "qrtz_locks  /* 存储的悲观锁信息表 */" {
   sched_name  /* 调度名称 */: varchar(120)
   lock_name  /* 悲观锁名称 */: varchar(40)
}
class node25 as "sys_config  /* 参数配置表 */" {
   config_name  /* 参数名称 */: varchar(100)
   config_key  /* 参数键名 */: varchar(100)
   config_value  /* 参数键值 */: varchar(500)
   config_type  /* 系统内置（Y是 N否） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   config_id  /* 参数主键 */: int(5)
}
class node40 as "sys_dept  /* 部门表 */" {
   parent_id  /* 父部门id */: bigint(20)
   ancestors  /* 祖级列表 */: varchar(50)
   dept_name  /* 部门名称 */: varchar(30)
   order_num  /* 显示顺序 */: int(4)
   leader  /* 负责人 */: varchar(20)
   phone  /* 联系电话 */: varchar(11)
   email  /* 邮箱 */: varchar(50)
   status  /* 部门状态（0正常 1停用） */: char(1)
   del_flag  /* 删除标志（0代表存在 2代表删除） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   dept_id  /* 部门id */: bigint(20)
}
class node0 as "sys_dict_data  /* 字典数据表 */" {
   dict_sort  /* 字典排序 */: int(4)
   dict_label  /* 字典标签 */: varchar(100)
   dict_value  /* 字典键值 */: varchar(100)
   dict_type  /* 字典类型 */: varchar(100)
   css_class  /* 样式属性（其他样式扩展） */: varchar(100)
   list_class  /* 表格回显样式 */: varchar(100)
   is_default  /* 是否默认（Y是 N否） */: char(1)
   status  /* 状态（0正常 1停用） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   dict_code  /* 字典编码 */: bigint(20)
}
class node19 as "sys_dict_type  /* 字典类型表 */" {
   dict_name  /* 字典名称 */: varchar(100)
   dict_type  /* 字典类型 */: varchar(100)
   status  /* 状态（0正常 1停用） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   dict_id  /* 字典主键 */: bigint(20)
}
class node30 as "sys_job  /* 定时任务调度表 */" {
   invoke_target  /* 调用目标字符串 */: varchar(500)
   cron_expression  /* cron执行表达式 */: varchar(255)
   misfire_policy  /* 计划执行错误策略（1立即执行 2执行一次 3放弃执行） */: varchar(20)
   concurrent  /* 是否并发执行（0允许 1禁止） */: char(1)
   status  /* 状态（0正常 1暂停） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注信息 */: varchar(500)
   job_id  /* 任务ID */: bigint(20)
   job_name  /* 任务名称 */: varchar(64)
   job_group  /* 任务组名 */: varchar(64)
}
class node9 as "sys_job_log  /* 定时任务调度日志表 */" {
   job_name  /* 任务名称 */: varchar(64)
   job_group  /* 任务组名 */: varchar(64)
   invoke_target  /* 调用目标字符串 */: varchar(500)
   job_message  /* 日志信息 */: varchar(500)
   status  /* 执行状态（0正常 1失败） */: char(1)
   exception_info  /* 异常信息 */: varchar(2000)
   create_time  /* 创建时间 */: datetime
   job_log_id  /* 任务日志ID */: bigint(20)
}
class node24 as "sys_logininfor  /* 系统访问记录 */" {
   user_name  /* 用户账号 */: varchar(50)
   ipaddr  /* 登录IP地址 */: varchar(128)
   login_location  /* 登录地点 */: varchar(255)
   browser  /* 浏览器类型 */: varchar(50)
   os  /* 操作系统 */: varchar(50)
   status  /* 登录状态（0成功 1失败） */: char(1)
   msg  /* 提示消息 */: varchar(255)
   login_time  /* 访问时间 */: datetime
   info_id  /* 访问ID */: bigint(20)
}
class node14 as "sys_menu  /* 菜单权限表 */" {
   menu_name  /* 菜单名称 */: varchar(50)
   parent_id  /* 父菜单ID */: bigint(20)
   order_num  /* 显示顺序 */: int(4)
   path  /* 路由地址 */: varchar(200)
   component  /* 组件路径 */: varchar(255)
   query  /* 路由参数 */: varchar(255)
   is_frame  /* 是否为外链（0是 1否） */: int(1)
   is_cache  /* 是否缓存（0缓存 1不缓存） */: int(1)
   menu_type  /* 菜单类型（M目录 C菜单 F按钮） */: char(1)
   visible  /* 菜单状态（0显示 1隐藏） */: char(1)
   status  /* 菜单状态（0正常 1停用） */: char(1)
   perms  /* 权限标识 */: varchar(100)
   icon  /* 菜单图标 */: varchar(100)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   menu_id  /* 菜单ID */: bigint(20)
}
class node3 as "sys_notice  /* 通知公告表 */" {
   notice_title  /* 公告标题 */: varchar(50)
   notice_type  /* 公告类型（1通知 2公告） */: char(1)
   notice_content  /* 公告内容 */: longblob
   status  /* 公告状态（0正常 1关闭） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(255)
   notice_id  /* 公告ID */: int(4)
}
class node32 as "sys_oper_log  /* 操作日志记录 */" {
   title  /* 模块标题 */: varchar(50)
   business_type  /* 业务类型（0其它 1新增 2修改 3删除） */: int(2)
   method  /* 方法名称 */: varchar(100)
   request_method  /* 请求方式 */: varchar(10)
   operator_type  /* 操作类别（0其它 1后台用户 2手机端用户） */: int(1)
   oper_name  /* 操作人员 */: varchar(50)
   dept_name  /* 部门名称 */: varchar(50)
   oper_url  /* 请求URL */: varchar(255)
   oper_ip  /* 主机地址 */: varchar(128)
   oper_location  /* 操作地点 */: varchar(255)
   oper_param  /* 请求参数 */: varchar(2000)
   json_result  /* 返回参数 */: varchar(2000)
   status  /* 操作状态（0正常 1异常） */: int(1)
   error_msg  /* 错误消息 */: varchar(2000)
   oper_time  /* 操作时间 */: datetime
   oper_id  /* 日志主键 */: bigint(20)
}
class node18 as "sys_post  /* 岗位信息表 */" {
   post_code  /* 岗位编码 */: varchar(64)
   post_name  /* 岗位名称 */: varchar(50)
   post_sort  /* 显示顺序 */: int(4)
   status  /* 状态（0正常 1停用） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime
   remark  /* 备注 */: varchar(500)
   post_id  /* 岗位ID */: bigint(20)
}
class node20 as "sys_role  /* 角色信息表 */" {
   role_name  /* 角色名称 */: varchar(30)
   role_key  /* 角色权限字符串 */: varchar(100)
   role_sort  /* 显示顺序 */: int(4)
   data_scope  /* 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限） */: char(1)
   menu_check_strictly  /* 菜单树选择项是否关联显示 */: tinyint(1)
   dept_check_strictly  /* 部门树选择项是否关联显示 */: tinyint(1)
   status  /* 角色状态（0正常 1停用） */: char(1)
   del_flag  /* 删除标志（0代表存在 2代表删除） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   role_id  /* 角色ID */: bigint(20)
}
class node38 as "sys_role_dept  /* 角色和部门关联表 */" {
   role_id  /* 角色ID */: bigint(20)
   dept_id  /* 部门ID */: bigint(20)
}
class node8 as "sys_role_menu  /* 角色和菜单关联表 */" {
   role_id  /* 角色ID */: bigint(20)
   menu_id  /* 菜单ID */: bigint(20)
}
class node37 as "sys_user  /* 用户信息表 */" {
   dept_id  /* 部门ID */: bigint(20)
   user_name  /* 用户账号 */: varchar(30)
   nick_name  /* 用户昵称 */: varchar(30)
   user_type  /* 用户类型（00系统用户） */: varchar(2)
   email  /* 用户邮箱 */: varchar(50)
   phonenumber  /* 手机号码 */: varchar(11)
   sex  /* 用户性别（0男 1女 2未知） */: char(1)
   avatar  /* 头像地址 */: varchar(100)
   password  /* 密码 */: varchar(100)
   status  /* 帐号状态（0正常 1停用） */: char(1)
   del_flag  /* 删除标志（0代表存在 2代表删除） */: char(1)
   login_ip  /* 最后登录IP */: varchar(128)
   login_date  /* 最后登录时间 */: datetime
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   remark  /* 备注 */: varchar(500)
   user_id  /* 用户ID */: bigint(20)
}
class node28 as "sys_user_post  /* 用户与岗位关联表 */" {
   user_id  /* 用户ID */: bigint(20)
   post_id  /* 岗位ID */: bigint(20)
}
class node7 as "sys_user_role  /* 用户和角色关联表 */" {
   user_id  /* 用户ID */: bigint(20)
   role_id  /* 角色ID */: bigint(20)
}
class node26 as "wms_area  /* 库区 */" {
   area_no  /* 编号 */: varchar(20)
   area_name  /* 名称 */: varchar(60)
   warehouse_id  /* 所属仓库ID */: bigint(20)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node21 as "wms_carrier  /* 承运商 */" {
   carrier_no  /* 编号 */: varchar(20)
   carrier_name  /* 名称 */: varchar(60)
   address  /* 地址 */: varchar(80)
   mobile  /* 手机号 */: varchar(13)
   tel  /* 座机号 */: varchar(13)
   contact  /* 联系人 */: varchar(30)
   level  /* 级别 */: varchar(10)
   email  /* Email */: varchar(50)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node13 as "wms_customer  /* 客户 */" {
   customer_no  /* 编号 */: varchar(20)
   customer_name  /* 名称 */: varchar(60)
   bank_name  /* 开户行 */: varchar(255)
   bank_account  /* 银行账户 */: varchar(40)
   receivable_amount  /* 应收款 */: decimal(10,2)
   address  /* 地址 */: varchar(200)
   mobile  /* 手机号 */: varchar(13)
   tel  /* 座机号 */: varchar(13)
   customer_person  /* 联系人 */: varchar(30)
   customer_level  /* 级别 */: varchar(10)
   email  /* Email */: varchar(50)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node5 as "wms_customer_transaction  /* 客户账户流水 */" {
   transaction_code  /* 交易编号 */: varchar(32)
   customer_id  /* 用户编号 */: varchar(32)
   transaction_type  /* 交易类型  1：结款  2：应付  */: varchar(2)
   transaction_amount  /* 交易金额 */: decimal(18,2)
   previous_balance  /* 上期余额 */: decimal(18,2)
   current_balance  /* 当前余额 */: decimal(18,2)
   shipment_order_id  /* 出库单号 */: bigint(20)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标志 */: tinyint(4)
   create_time  /* 创建时间 */: datetime
   update_time  /* 更新时间 */: datetime
   id  /* id */: int(11)
}
class node1 as "wms_delivery  /* 发货记录 */" {
   shipment_order_id  /* 出库单主表Id */: bigint(20)
   carrier_id  /* 承运商Id */: bigint(20)
   delivery_date  /* 发货日期 */: datetime(3)
   tracking_no  /* 快递单号 */: varchar(50)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node12 as "wms_inventory  /* 库存 */" {
   item_id  /* 物料ID */: bigint(20)
   rack_id  /* 货架id */: bigint(20)
   quantity  /* 库存 */: decimal(20,2)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   id: bigint(20)
}
class node23 as "wms_inventory_check  /* 库存盘点单据 */" {
   inventory_check_no  /* 库存盘点单号，系统自动生成 */: varchar(22)
   inventory_check_type  /* 库存盘点类型 */: int(11)
   inventory_check_status  /* 库存盘点单状态11：盘点中 22：已完成 */: tinyint(4)
   inventory_check_total  /* 盈亏数 */: decimal(20,2)
   check_status  /* 审核状态 */: tinyint(4)
   check_user_id  /* 审核人 */: bigint(20)
   check_time  /* 审核时间 */: datetime(3)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   rack_id  /* 货架 */: bigint(20)
   attachment  /* 附件文件 */: varchar(255)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node22 as "wms_inventory_check_detail  /* 库存盘点单据详情 */" {
   inventory_check_id  /* 库存盘点单 */: bigint(20)
   item_id  /* 物料 */: bigint(20)
   quantity  /* 库存数量 */: decimal(20,2)
   check_quantity  /* 盘点数量 */: decimal(20,2)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   rack_id  /* 货架 */: bigint(20)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node41 as "wms_inventory_history  /* 库存记录 */" {
   form_id  /* 操作id（出库、入库、库存移动表单id） */: bigint(20)
   form_type  /* 操作类型 */: int(11)
   item_id  /* 物料ID */: bigint(20)
   rack_id  /* 货架id */: bigint(20)
   quantity  /* 库存变化 */: decimal(20,2)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   id: bigint(20)
}
class node33 as "wms_inventory_movement  /* 库存移动 */" {
   inventory_movement_no  /* 编号 */: varchar(30)
   source_rack_id  /* 原货架Id */: bigint(20)
   target_rack_id  /* 目标货架 */: bigint(20)
   status  /* 状态 */: tinyint(4)
   check_status  /* 审核状态 */: tinyint(4)
   check_user_id  /* 审核人 */: bigint(20)
   check_time  /* 审核时间 */: datetime(3)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node11 as "wms_inventory_movement_detail  /* 库存移动详情 */" {
   inventory_movement_id  /* 库存移动Id */: bigint(20)
   item_id  /* 物料 */: bigint(20)
   plan_quantity  /* 计划数量 */: decimal(20,2)
   real_quantity  /* 实际数量 */: decimal(20,2)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   source_rack_id  /* 源货架 */: bigint(20)
   source_warehouse_id  /* 源仓库 */: bigint(20)
   source_area_id  /* 源库区 */: bigint(20)
   move_status  /* 移库状态 */: tinyint(4)
   target_rack_id  /* 目标货架 */: bigint(20)
   target_warehouse_id  /* 目标仓库 */: bigint(20)
   target_area_id  /* 目标库区 */: bigint(20)
   id: bigint(20)
}
class node43 as "wms_inventory_settlement  /* 库存结算单 */" {
   inventory_settlement_no  /* 库存结算单号 */: varchar(22)
   inventory_settlement_status  /* 库存结算单状态11：结算中 22：已完成 */: tinyint(4)
   inventory_settlement_start_time  /* 库存结算周期开始时间 */: datetime
   inventory_settlement_end_time  /* 库存结算周期结束时间 */: datetime
   settlement_type  /* 结算类型,1:月结，2:年结 */: int(11)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node10 as "wms_inventory_settlement_detail  /* 库存结算明细 */" {
   settlement_id  /* 结算单id */: bigint(20)
   settlement_type  /* 结算类型,1:月结，2:年结 */: int(11)
   item_id  /* 物料id */: bigint(20)
   item_no  /* 编号 */: varchar(20)
   item_name  /* 名称 */: varchar(60)
   warehouse_id  /* 仓库id */: bigint(20)
   warehouse_no  /* 仓库编号 */: varchar(20)
   warehouse_name  /* 仓库名称 */: varchar(50)
   area_id  /* 库区id */: bigint(20)
   area_no  /* 库区编号 */: varchar(20)
   area_name  /* 库区名称 */: varchar(60)
   previous_balance  /* 上期结存 */: decimal(20,2)
   current_enter  /* 本期入库 */: decimal(20,2)
   current_out  /* 本期出库 */: decimal(20,2)
   current_check  /* 本期盘点 */: decimal(20,2)
   current_balance  /* 本期结存 */: decimal(20,2)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node16 as "wms_item  /* 物料 */" {
   item_no  /* 编号 */: varchar(20)
   item_name  /* 名称 */: varchar(60)
   specification  /* 规格 */: varchar(255)
   item_type  /* 分类 */: varchar(20)
   unit  /* 单位类别 */: varchar(20)
   unit_price  /* 单价 */: decimal(10,2)
   rack_id  /* 所属货架 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   warehouse_id  /* 所属仓库 */: bigint(20)
   quantity  /* 安全库存 */: decimal(20,2)
   production_date  /* 生产日期 */: datetime(3)
   expiry_date  /* 有效期 */: datetime(3)
   batch  /* 批次 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node4 as "wms_item_type  /* 物料类型表 */" {
   parent_id  /* 父物料类型id */: bigint(20)
   ancestors  /* 祖级列表 */: varchar(50)
   type_name  /* 物料类型名称 */: varchar(30)
   order_num  /* 显示顺序 */: int(11)
   status  /* 物料类型状态（0正常 1停用） */: char(1)
   del_flag  /* 删除标志（0代表存在 2代表删除） */: char(1)
   create_by  /* 创建者 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 更新者 */: bigint(20)
   update_time  /* 更新时间 */: datetime(3)
   item_type_id  /* 物料类型id */: bigint(20)
}
class node35 as "wms_rack  /* 货架 */" {
   rack_no  /* 编号 */: varchar(20)
   rack_name  /* 名称 */: varchar(60)
   area_id  /* 所属库区 */: bigint(20)
   warehouse_id  /* 所属仓库 */: bigint(20)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node6 as "wms_receipt_order  /* 入库单 */" {
   receipt_order_no  /* 入库单号 */: varchar(32)
   receipt_order_type  /* 入库类型 */: int(11)
   supplier_id  /* 供应商 */: bigint(20)
   order_no  /* 订单号 */: varchar(32)
   payable_amount  /* 订单金额 */: decimal(10,2)
   receipt_order_status  /* 入库状态 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   wave_no  /* 波次号 */: varchar(32)
   id: bigint(20)
}
class node27 as "wms_receipt_order_detail  /* 入库单详情 */" {
   receipt_order_id  /* 入库单号 */: bigint(20)
   item_id  /* 物料 */: bigint(20)
   plan_quantity  /* 计划数量 */: decimal(20,2)
   real_quantity  /* 实际数量 */: decimal(20,2)
   rack_id  /* 所属货架 */: bigint(20)
   money  /* 金额 */: decimal(10,2)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   receipt_order_status  /* 入库状态 */: tinyint(4)
   id: bigint(20)
}
class node34 as "wms_shipment_order  /* 出库单 */" {
   shipment_order_no  /* 出库单号，系统自动生成 */: varchar(22)
   shipment_order_type  /* 出库类型 */: int(11)
   order_no  /* 出库订单 */: varchar(50)
   customer_id  /* 客户 */: bigint(20)
   receivable_amount  /* 订单金额 */: decimal(10,2)
   shipment_order_status  /* 出库单状态 */: tinyint(4)
   check_status  /* 审核状态 */: tinyint(4)
   check_user_id  /* 审核人 */: bigint(20)
   check_time  /* 审核时间 */: datetime(3)
   wave_no  /* 波次号 */: varchar(32)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node31 as "wms_shipment_order_detail  /* 出库单详情 */" {
   shipment_order_id  /* 出库单 */: bigint(20)
   item_id  /* 物料 */: bigint(20)
   plan_quantity  /* 计划数量 */: decimal(20,2)
   real_quantity  /* 实际数量 */: decimal(20,2)
   rack_id  /* 货架 */: bigint(20)
   money  /* 金额 */: decimal(10,2)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   warehouse_id  /* 所属仓库 */: bigint(20)
   area_id  /* 所属库区 */: bigint(20)
   shipment_order_status  /* 出库状态 */: tinyint(4)
   id: bigint(20)
}
class node39 as "wms_supplier  /* 供应商 */" {
   supplier_no  /* 编号 */: varchar(20)
   supplier_name  /* 名称 */: varchar(60)
   bank_name  /* 开户行 */: varchar(255)
   bank_account  /* 银行账户 */: varchar(40)
   payable_amount  /* 应付款 */: decimal(10,2)
   address  /* 地址 */: varchar(80)
   mobile_no  /* 手机号 */: varchar(13)
   tel_no  /* 座机号 */: varchar(13)
   contact  /* 联系人 */: varchar(30)
   level  /* 级别 */: varchar(10)
   email  /* Email */: varchar(50)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node17 as "wms_supplier_transaction  /* 供应商账户流水 */" {
   transaction_code  /* 交易编号 */: varchar(32)
   supplier_id  /* 供应商编号 */: varchar(32)
   transaction_type  /* 交易类型  1：结款  2：应付  */: varchar(2)
   transaction_amount  /* 交易金额 */: decimal(18,2)
   previous_balance  /* 上期余额 */: decimal(18,2)
   current_balance  /* 当前余额 */: decimal(18,2)
   receipt_order_id  /* 入库单号 */: bigint(20)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标志 */: tinyint(4)
   create_time  /* 创建时间 */: datetime
   update_time  /* 更新时间 */: datetime
   id  /* id */: int(11)
}
class node15 as "wms_warehouse  /* 仓库 */" {
   warehouse_no  /* 编号 */: varchar(20)
   warehouse_name  /* 名称 */: varchar(50)
   del_flag  /* 删除标识 */: tinyint(4)
   remark  /* 备注 */: varchar(255)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   id: bigint(20)
}
class node2 as "wms_wave  /* 波次 */" {
   wave_no  /* 波次号 */: varchar(32)
   status  /* 状态 */: varchar(255)
   remark  /* 备注 */: varchar(255)
   del_flag  /* 删除标识 */: tinyint(4)
   create_by  /* 创建人 */: bigint(20)
   create_time  /* 创建时间 */: datetime(3)
   update_by  /* 修改人 */: bigint(20)
   update_time  /* 修改时间 */: datetime(3)
   type  /* 1：入库单  2：出库单 */: int(255)
   id: bigint(20)
}

@enduml
